// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {scanner} from '../models';
import {config} from '../models';
import {sync} from '../models';

export function AddExtensions(arg1:Array<string>):Promise<void>;

export function ApplyBatch(arg1:context.Context,arg2:Array<scanner.ScanResult>):Promise<void>;

export function Collector(arg1:context.Context,arg2:number,arg3:any):Promise<Record<string, boolean>>;

export function GetConfig():Promise<scanner.ScannerConfigSnapshot>;

export function GetPredefinedPalette():Promise<Array<config.PaletteColor>>;

export function IsExtensionAllowed(arg1:string):Promise<boolean>;

export function ListenToWatcher(arg1:any):Promise<void>;

export function RemoveExtension(arg1:string):Promise<void>;

export function ScanFile(arg1:context.Context,arg2:string):Promise<void>;

export function Shutdown():Promise<void>;

export function StartScan():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopScan():Promise<void>;

export function TryHeuristicMatch(arg1:context.Context,arg2:number,arg3:string):Promise<string|boolean>;

export function Worker(arg1:context.Context,arg2:sync.WaitGroup,arg3:any,arg4:any):Promise<void>;
