// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddExtensions(arg1) {
  return window['go']['scanner']['Scanner']['AddExtensions'](arg1);
}

export function Collector(arg1, arg2, arg3) {
  return window['go']['scanner']['Scanner']['Collector'](arg1, arg2, arg3);
}

export function GetConfig() {
  return window['go']['scanner']['Scanner']['GetConfig']();
}

export function GetPredefinedPalette() {
  return window['go']['scanner']['Scanner']['GetPredefinedPalette']();
}

export function InsertAssets(arg1, arg2) {
  return window['go']['scanner']['Scanner']['InsertAssets'](arg1, arg2);
}

export function IsExtensionAllowed(arg1) {
  return window['go']['scanner']['Scanner']['IsExtensionAllowed'](arg1);
}

export function RemoveExtension(arg1) {
  return window['go']['scanner']['Scanner']['RemoveExtension'](arg1);
}

export function StartScan() {
  return window['go']['scanner']['Scanner']['StartScan']();
}

export function Startup(arg1) {
  return window['go']['scanner']['Scanner']['Startup'](arg1);
}

export function StopScan() {
  return window['go']['scanner']['Scanner']['StopScan']();
}

export function Worker(arg1, arg2, arg3, arg4) {
  return window['go']['scanner']['Scanner']['Worker'](arg1, arg2, arg3, arg4);
}
