// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const countAssets = `-- name: CountAssets :one
SELECT count(*) FROM assets
WHERE is_deleted = 0
`

func (q *Queries) CountAssets(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countAssetsStmt, countAssets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (
    scan_folder_id, file_name, file_path, file_type, file_size,
    thumbnail_path, last_modified, last_scanned, file_hash,
    image_width, image_height, dominant_color, bit_depth, has_alpha_channel
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, scan_folder_id, parent_asset_id, file_name, file_path, file_type, file_size, thumbnail_path, rating, description, is_favorite, image_width, image_height, dominant_color, bit_depth, has_alpha_channel, date_added, last_scanned, last_modified, file_hash, is_deleted, deleted_at
`

type CreateAssetParams struct {
	ScanFolderID    sql.NullInt64  `json:"scan_folder_id"`
	FileName        string         `json:"file_name"`
	FilePath        string         `json:"file_path"`
	FileType        string         `json:"file_type"`
	FileSize        int64          `json:"file_size"`
	ThumbnailPath   string         `json:"thumbnail_path"`
	LastModified    time.Time      `json:"last_modified"`
	LastScanned     time.Time      `json:"last_scanned"`
	FileHash        sql.NullString `json:"file_hash"`
	ImageWidth      sql.NullInt64  `json:"image_width"`
	ImageHeight     sql.NullInt64  `json:"image_height"`
	DominantColor   sql.NullString `json:"dominant_color"`
	BitDepth        sql.NullInt64  `json:"bit_depth"`
	HasAlphaChannel sql.NullBool   `json:"has_alpha_channel"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.queryRow(ctx, q.createAssetStmt, createAsset,
		arg.ScanFolderID,
		arg.FileName,
		arg.FilePath,
		arg.FileType,
		arg.FileSize,
		arg.ThumbnailPath,
		arg.LastModified,
		arg.LastScanned,
		arg.FileHash,
		arg.ImageWidth,
		arg.ImageHeight,
		arg.DominantColor,
		arg.BitDepth,
		arg.HasAlphaChannel,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.ScanFolderID,
		&i.ParentAssetID,
		&i.FileName,
		&i.FilePath,
		&i.FileType,
		&i.FileSize,
		&i.ThumbnailPath,
		&i.Rating,
		&i.Description,
		&i.IsFavorite,
		&i.ImageWidth,
		&i.ImageHeight,
		&i.DominantColor,
		&i.BitDepth,
		&i.HasAlphaChannel,
		&i.DateAdded,
		&i.LastScanned,
		&i.LastModified,
		&i.FileHash,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return i, err
}

const getAsset = `-- name: GetAsset :one
SELECT id, scan_folder_id, parent_asset_id, file_name, file_path, file_type, file_size, thumbnail_path, rating, description, is_favorite, image_width, image_height, dominant_color, bit_depth, has_alpha_channel, date_added, last_scanned, last_modified, file_hash, is_deleted, deleted_at FROM assets
WHERE id = ? LIMIT 1
`

func (q *Queries) GetAsset(ctx context.Context, id int64) (Asset, error) {
	row := q.queryRow(ctx, q.getAssetStmt, getAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.ScanFolderID,
		&i.ParentAssetID,
		&i.FileName,
		&i.FilePath,
		&i.FileType,
		&i.FileSize,
		&i.ThumbnailPath,
		&i.Rating,
		&i.Description,
		&i.IsFavorite,
		&i.ImageWidth,
		&i.ImageHeight,
		&i.DominantColor,
		&i.BitDepth,
		&i.HasAlphaChannel,
		&i.DateAdded,
		&i.LastScanned,
		&i.LastModified,
		&i.FileHash,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
SELECT id, scan_folder_id, parent_asset_id, file_name, file_path, file_type, file_size, thumbnail_path, rating, description, is_favorite, image_width, image_height, dominant_color, bit_depth, has_alpha_channel, date_added, last_scanned, last_modified, file_hash, is_deleted, deleted_at FROM assets
WHERE is_deleted = 0
ORDER BY date_added DESC
LIMIT ? OFFSET ?
`

type ListAssetsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListAssets(ctx context.Context, arg ListAssetsParams) ([]Asset, error) {
	rows, err := q.query(ctx, q.listAssetsStmt, listAssets, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.ScanFolderID,
			&i.ParentAssetID,
			&i.FileName,
			&i.FilePath,
			&i.FileType,
			&i.FileSize,
			&i.ThumbnailPath,
			&i.Rating,
			&i.Description,
			&i.IsFavorite,
			&i.ImageWidth,
			&i.ImageHeight,
			&i.DominantColor,
			&i.BitDepth,
			&i.HasAlphaChannel,
			&i.DateAdded,
			&i.LastScanned,
			&i.LastModified,
			&i.FileHash,
			&i.IsDeleted,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssetScanStatus = `-- name: UpdateAssetScanStatus :exec
UPDATE assets
SET last_scanned = ?, file_size = ?, last_modified = ?
WHERE id = ?
`

type UpdateAssetScanStatusParams struct {
	LastScanned  time.Time `json:"last_scanned"`
	FileSize     int64     `json:"file_size"`
	LastModified time.Time `json:"last_modified"`
	ID           int64     `json:"id"`
}

func (q *Queries) UpdateAssetScanStatus(ctx context.Context, arg UpdateAssetScanStatusParams) error {
	_, err := q.exec(ctx, q.updateAssetScanStatusStmt, updateAssetScanStatus,
		arg.LastScanned,
		arg.FileSize,
		arg.LastModified,
		arg.ID,
	)
	return err
}
