// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.countAssetsStmt, err = db.PrepareContext(ctx, countAssets); err != nil {
		return nil, fmt.Errorf("error preparing query CountAssets: %w", err)
	}
	if q.createAssetStmt, err = db.PrepareContext(ctx, createAsset); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAsset: %w", err)
	}
	if q.getAssetStmt, err = db.PrepareContext(ctx, getAsset); err != nil {
		return nil, fmt.Errorf("error preparing query GetAsset: %w", err)
	}
	if q.listAssetsStmt, err = db.PrepareContext(ctx, listAssets); err != nil {
		return nil, fmt.Errorf("error preparing query ListAssets: %w", err)
	}
	if q.updateAssetScanStatusStmt, err = db.PrepareContext(ctx, updateAssetScanStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAssetScanStatus: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.countAssetsStmt != nil {
		if cerr := q.countAssetsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countAssetsStmt: %w", cerr)
		}
	}
	if q.createAssetStmt != nil {
		if cerr := q.createAssetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAssetStmt: %w", cerr)
		}
	}
	if q.getAssetStmt != nil {
		if cerr := q.getAssetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAssetStmt: %w", cerr)
		}
	}
	if q.listAssetsStmt != nil {
		if cerr := q.listAssetsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAssetsStmt: %w", cerr)
		}
	}
	if q.updateAssetScanStatusStmt != nil {
		if cerr := q.updateAssetScanStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAssetScanStatusStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                        DBTX
	tx                        *sql.Tx
	countAssetsStmt           *sql.Stmt
	createAssetStmt           *sql.Stmt
	getAssetStmt              *sql.Stmt
	listAssetsStmt            *sql.Stmt
	updateAssetScanStatusStmt *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                        tx,
		tx:                        tx,
		countAssetsStmt:           q.countAssetsStmt,
		createAssetStmt:           q.createAssetStmt,
		getAssetStmt:              q.getAssetStmt,
		listAssetsStmt:            q.listAssetsStmt,
		updateAssetScanStatusStmt: q.updateAssetScanStatusStmt,
	}
}
