// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: material_sets.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const addAssetToMaterialSet = `-- name: AddAssetToMaterialSet :exec
INSERT OR IGNORE INTO asset_material_sets (material_set_id, asset_id) VALUES (?, ?)
`

type AddAssetToMaterialSetParams struct {
	MaterialSetID int64 `json:"materialSetId"`
	AssetID       int64 `json:"assetId"`
}

func (q *Queries) AddAssetToMaterialSet(ctx context.Context, arg AddAssetToMaterialSetParams) error {
	_, err := q.exec(ctx, q.addAssetToMaterialSetStmt, addAssetToMaterialSet, arg.MaterialSetID, arg.AssetID)
	return err
}

const createMaterialSet = `-- name: CreateMaterialSet :one
INSERT INTO material_sets (
    name, description, cover_asset_id, custom_cover_url, custom_color
) VALUES (?, ?, ?, ?, ?)
RETURNING id, name, description, cover_asset_id, custom_cover_url, custom_color, date_added, last_modified
`

type CreateMaterialSetParams struct {
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	CoverAssetID   sql.NullInt64  `json:"coverAssetId"`
	CustomCoverUrl sql.NullString `json:"customCoverUrl"`
	CustomColor    sql.NullString `json:"customColor"`
}

func (q *Queries) CreateMaterialSet(ctx context.Context, arg CreateMaterialSetParams) (MaterialSet, error) {
	row := q.queryRow(ctx, q.createMaterialSetStmt, createMaterialSet,
		arg.Name,
		arg.Description,
		arg.CoverAssetID,
		arg.CustomCoverUrl,
		arg.CustomColor,
	)
	var i MaterialSet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CoverAssetID,
		&i.CustomCoverUrl,
		&i.CustomColor,
		&i.DateAdded,
		&i.LastModified,
	)
	return i, err
}

const deleteMaterialSet = `-- name: DeleteMaterialSet :exec
DELETE FROM material_sets WHERE id = ?
`

func (q *Queries) DeleteMaterialSet(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteMaterialSetStmt, deleteMaterialSet, id)
	return err
}

const getMaterialSetById = `-- name: GetMaterialSetById :one
SELECT id, name, description, cover_asset_id, custom_cover_url, custom_color, date_added, last_modified FROM material_sets WHERE id = ? LIMIT 1
`

func (q *Queries) GetMaterialSetById(ctx context.Context, id int64) (MaterialSet, error) {
	row := q.queryRow(ctx, q.getMaterialSetByIdStmt, getMaterialSetById, id)
	var i MaterialSet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CoverAssetID,
		&i.CustomCoverUrl,
		&i.CustomColor,
		&i.DateAdded,
		&i.LastModified,
	)
	return i, err
}

const listAssetsInMaterialSet = `-- name: ListAssetsInMaterialSet :many
SELECT a.id, a.scan_folder_id, a.parent_asset_id, a.file_name, a.file_path, a.file_type, a.file_size, a.thumbnail_path, a.rating, a.description, a.is_favorite, a.image_width, a.image_height, a.dominant_color, a.bit_depth, a.has_alpha_channel, a.date_added, a.last_scanned, a.last_modified, a.file_hash, a.is_deleted, a.deleted_at, a.is_hidden FROM assets a
JOIN asset_material_sets ams ON a.id = ams.asset_id
WHERE ams.material_set_id = ? AND a.is_deleted = 0
ORDER BY a.date_added DESC
LIMIT ? OFFSET ?
`

type ListAssetsInMaterialSetParams struct {
	MaterialSetID int64 `json:"materialSetId"`
	Limit         int64 `json:"limit"`
	Offset        int64 `json:"offset"`
}

func (q *Queries) ListAssetsInMaterialSet(ctx context.Context, arg ListAssetsInMaterialSetParams) ([]Asset, error) {
	rows, err := q.query(ctx, q.listAssetsInMaterialSetStmt, listAssetsInMaterialSet, arg.MaterialSetID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.ScanFolderID,
			&i.ParentAssetID,
			&i.FileName,
			&i.FilePath,
			&i.FileType,
			&i.FileSize,
			&i.ThumbnailPath,
			&i.Rating,
			&i.Description,
			&i.IsFavorite,
			&i.ImageWidth,
			&i.ImageHeight,
			&i.DominantColor,
			&i.BitDepth,
			&i.HasAlphaChannel,
			&i.DateAdded,
			&i.LastScanned,
			&i.LastModified,
			&i.FileHash,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.IsHidden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialSets = `-- name: ListMaterialSets :many
SELECT
    ms.id, ms.name, ms.description, ms.cover_asset_id, ms.custom_cover_url, ms.custom_color, ms.date_added, ms.last_modified,
    (SELECT COUNT(*) FROM asset_material_sets ams WHERE ams.material_set_id = ms.id) as total_assets
FROM material_sets ms
ORDER BY ms.name
`

type ListMaterialSetsRow struct {
	ID             int64          `json:"id"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	CoverAssetID   sql.NullInt64  `json:"coverAssetId"`
	CustomCoverUrl sql.NullString `json:"customCoverUrl"`
	CustomColor    sql.NullString `json:"customColor"`
	DateAdded      time.Time      `json:"dateAdded"`
	LastModified   time.Time      `json:"lastModified"`
	TotalAssets    int64          `json:"totalAssets"`
}

func (q *Queries) ListMaterialSets(ctx context.Context) ([]ListMaterialSetsRow, error) {
	rows, err := q.query(ctx, q.listMaterialSetsStmt, listMaterialSets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMaterialSetsRow
	for rows.Next() {
		var i ListMaterialSetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CoverAssetID,
			&i.CustomCoverUrl,
			&i.CustomColor,
			&i.DateAdded,
			&i.LastModified,
			&i.TotalAssets,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAssetFromMaterialSet = `-- name: RemoveAssetFromMaterialSet :exec
DELETE FROM asset_material_sets WHERE material_set_id = ? AND asset_id = ?
`

type RemoveAssetFromMaterialSetParams struct {
	MaterialSetID int64 `json:"materialSetId"`
	AssetID       int64 `json:"assetId"`
}

func (q *Queries) RemoveAssetFromMaterialSet(ctx context.Context, arg RemoveAssetFromMaterialSetParams) error {
	_, err := q.exec(ctx, q.removeAssetFromMaterialSetStmt, removeAssetFromMaterialSet, arg.MaterialSetID, arg.AssetID)
	return err
}

const updateMaterialSet = `-- name: UpdateMaterialSet :exec
UPDATE material_sets
SET
    name = ?, description = ?, cover_asset_id = ?,
    custom_cover_url = ?, custom_color = ?,
    last_modified = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateMaterialSetParams struct {
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	CoverAssetID   sql.NullInt64  `json:"coverAssetId"`
	CustomCoverUrl sql.NullString `json:"customCoverUrl"`
	CustomColor    sql.NullString `json:"customColor"`
	ID             int64          `json:"id"`
}

func (q *Queries) UpdateMaterialSet(ctx context.Context, arg UpdateMaterialSetParams) error {
	_, err := q.exec(ctx, q.updateMaterialSetStmt, updateMaterialSet,
		arg.Name,
		arg.Description,
		arg.CoverAssetID,
		arg.CustomCoverUrl,
		arg.CustomColor,
		arg.ID,
	)
	return err
}
