// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Asset struct {
	ID              int64          `json:"id"`
	ScanFolderID    sql.NullInt64  `json:"scan_folder_id"`
	ParentAssetID   sql.NullInt64  `json:"parent_asset_id"`
	FileName        string         `json:"file_name"`
	FilePath        string         `json:"file_path"`
	FileType        string         `json:"file_type"`
	FileSize        int64          `json:"file_size"`
	ThumbnailPath   string         `json:"thumbnail_path"`
	Rating          int64          `json:"rating"`
	Description     sql.NullString `json:"description"`
	IsFavorite      sql.NullBool   `json:"is_favorite"`
	ImageWidth      sql.NullInt64  `json:"image_width"`
	ImageHeight     sql.NullInt64  `json:"image_height"`
	DominantColor   sql.NullString `json:"dominant_color"`
	BitDepth        sql.NullInt64  `json:"bit_depth"`
	HasAlphaChannel sql.NullBool   `json:"has_alpha_channel"`
	DateAdded       time.Time      `json:"date_added"`
	LastScanned     time.Time      `json:"last_scanned"`
	LastModified    time.Time      `json:"last_modified"`
	FileHash        sql.NullString `json:"file_hash"`
	IsDeleted       bool           `json:"is_deleted"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
}

type ScanFolder struct {
	ID          int64        `json:"id"`
	Path        string       `json:"path"`
	IsActive    bool         `json:"is_active"`
	LastScanned sql.NullTime `json:"last_scanned"`
	DateAdded   time.Time    `json:"date_added"`
}
