// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Asset struct {
	ID              int64          `json:"id"`
	ScanFolderID    sql.NullInt64  `json:"scanFolderId"`
	ParentAssetID   sql.NullInt64  `json:"parentAssetId"`
	FileName        string         `json:"fileName"`
	FilePath        string         `json:"filePath"`
	FileType        string         `json:"fileType"`
	FileSize        int64          `json:"fileSize"`
	ThumbnailPath   string         `json:"thumbnailPath"`
	Rating          int64          `json:"rating"`
	Description     sql.NullString `json:"description"`
	IsFavorite      sql.NullBool   `json:"isFavorite"`
	ImageWidth      sql.NullInt64  `json:"imageWidth"`
	ImageHeight     sql.NullInt64  `json:"imageHeight"`
	DominantColor   sql.NullString `json:"dominantColor"`
	BitDepth        sql.NullInt64  `json:"bitDepth"`
	HasAlphaChannel sql.NullBool   `json:"hasAlphaChannel"`
	DateAdded       time.Time      `json:"dateAdded"`
	LastScanned     time.Time      `json:"lastScanned"`
	LastModified    time.Time      `json:"lastModified"`
	FileHash        sql.NullString `json:"fileHash"`
	IsDeleted       bool           `json:"isDeleted"`
	DeletedAt       sql.NullTime   `json:"deletedAt"`
}

type AssetMaterialSet struct {
	AssetID       int64 `json:"assetId"`
	MaterialSetID int64 `json:"materialSetId"`
}

type AssetTag struct {
	AssetID int64 `json:"assetId"`
	TagID   int64 `json:"tagId"`
}

type MaterialSet struct {
	ID             int64          `json:"id"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	CoverAssetID   sql.NullInt64  `json:"coverAssetId"`
	CustomCoverUrl sql.NullString `json:"customCoverUrl"`
	CustomColor    sql.NullString `json:"customColor"`
	DateAdded      time.Time      `json:"dateAdded"`
	LastModified   time.Time      `json:"lastModified"`
}

type SavedSearch struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	FilterJson string    `json:"filterJson"`
	DateAdded  time.Time `json:"dateAdded"`
}

type ScanFolder struct {
	ID          int64        `json:"id"`
	Path        string       `json:"path"`
	IsActive    bool         `json:"isActive"`
	LastScanned sql.NullTime `json:"lastScanned"`
	DateAdded   time.Time    `json:"dateAdded"`
	IsDeleted   bool         `json:"isDeleted"`
}

type SystemSetting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Tag struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	DateCreated time.Time `json:"dateCreated"`
}
