// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: saved_searches.sql

package database

import (
	"context"
)

const createSavedSearch = `-- name: CreateSavedSearch :one
INSERT INTO saved_searches (name, filter_json) VALUES (?, ?) RETURNING id, name, filter_json, date_added
`

type CreateSavedSearchParams struct {
	Name       string `json:"name"`
	FilterJson string `json:"filterJson"`
}

func (q *Queries) CreateSavedSearch(ctx context.Context, arg CreateSavedSearchParams) (SavedSearch, error) {
	row := q.queryRow(ctx, q.createSavedSearchStmt, createSavedSearch, arg.Name, arg.FilterJson)
	var i SavedSearch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FilterJson,
		&i.DateAdded,
	)
	return i, err
}

const deleteSavedSearch = `-- name: DeleteSavedSearch :exec
DELETE FROM saved_searches WHERE id = ?
`

func (q *Queries) DeleteSavedSearch(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteSavedSearchStmt, deleteSavedSearch, id)
	return err
}

const listSavedSearches = `-- name: ListSavedSearches :many
SELECT id, name, filter_json, date_added FROM saved_searches ORDER BY name
`

func (q *Queries) ListSavedSearches(ctx context.Context) ([]SavedSearch, error) {
	rows, err := q.query(ctx, q.listSavedSearchesStmt, listSavedSearches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavedSearch
	for rows.Next() {
		var i SavedSearch
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FilterJson,
			&i.DateAdded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
