// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scan_folders.sql

package database

import (
	"context"
)

const createScanFolder = `-- name: CreateScanFolder :one
INSERT INTO scan_folders (path, is_active, last_scanned, is_deleted)
VALUES (?, 1, NULL, 0)
RETURNING id, path, is_active, last_scanned, date_added, is_deleted
`

func (q *Queries) CreateScanFolder(ctx context.Context, path string) (ScanFolder, error) {
	row := q.queryRow(ctx, q.createScanFolderStmt, createScanFolder, path)
	var i ScanFolder
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.IsActive,
		&i.LastScanned,
		&i.DateAdded,
		&i.IsDeleted,
	)
	return i, err
}

const getScanFolderById = `-- name: GetScanFolderById :one
SELECT id, path, is_active, last_scanned, date_added, is_deleted FROM scan_folders
WHERE id = ? LIMIT 1
`

func (q *Queries) GetScanFolderById(ctx context.Context, id int64) (ScanFolder, error) {
	row := q.queryRow(ctx, q.getScanFolderByIdStmt, getScanFolderById, id)
	var i ScanFolder
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.IsActive,
		&i.LastScanned,
		&i.DateAdded,
		&i.IsDeleted,
	)
	return i, err
}

const getScanFolderByPath = `-- name: GetScanFolderByPath :one
SELECT id, path, is_active, last_scanned, date_added, is_deleted FROM scan_folders
WHERE path = ? LIMIT 1
`

func (q *Queries) GetScanFolderByPath(ctx context.Context, path string) (ScanFolder, error) {
	row := q.queryRow(ctx, q.getScanFolderByPathStmt, getScanFolderByPath, path)
	var i ScanFolder
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.IsActive,
		&i.LastScanned,
		&i.DateAdded,
		&i.IsDeleted,
	)
	return i, err
}

const listScanFolders = `-- name: ListScanFolders :many
SELECT id, path, is_active, last_scanned, date_added, is_deleted FROM scan_folders
WHERE is_deleted = 0
ORDER BY path ASC
`

func (q *Queries) ListScanFolders(ctx context.Context) ([]ScanFolder, error) {
	rows, err := q.query(ctx, q.listScanFoldersStmt, listScanFolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanFolder
	for rows.Next() {
		var i ScanFolder
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.IsActive,
			&i.LastScanned,
			&i.DateAdded,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreScanFolder = `-- name: RestoreScanFolder :exec
UPDATE scan_folders
SET is_deleted = 0
WHERE id = ?
`

func (q *Queries) RestoreScanFolder(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.restoreScanFolderStmt, restoreScanFolder, id)
	return err
}

const softDeleteScanFolder = `-- name: SoftDeleteScanFolder :exec
UPDATE scan_folders
SET is_deleted = 1
WHERE id = ?
`

func (q *Queries) SoftDeleteScanFolder(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.softDeleteScanFolderStmt, softDeleteScanFolder, id)
	return err
}

const updateScanFolderLastScanned = `-- name: UpdateScanFolderLastScanned :exec
UPDATE scan_folders
SET last_scanned = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateScanFolderLastScanned(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.updateScanFolderLastScannedStmt, updateScanFolderLastScanned, id)
	return err
}

const updateScanFolderStatus = `-- name: UpdateScanFolderStatus :exec
UPDATE scan_folders
SET is_active = ?
WHERE id = ?
`

type UpdateScanFolderStatusParams struct {
	IsActive bool  `json:"isActive"`
	ID       int64 `json:"id"`
}

func (q *Queries) UpdateScanFolderStatus(ctx context.Context, arg UpdateScanFolderStatusParams) error {
	_, err := q.exec(ctx, q.updateScanFolderStatusStmt, updateScanFolderStatus, arg.IsActive, arg.ID)
	return err
}
