// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_settings.sql

package database

import (
	"context"
)

const getSystemSetting = `-- name: GetSystemSetting :one
SELECT value FROM system_settings WHERE key = ? LIMIT 1
`

func (q *Queries) GetSystemSetting(ctx context.Context, key string) (string, error) {
	row := q.queryRow(ctx, q.getSystemSettingStmt, getSystemSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setSystemSetting = `-- name: SetSystemSetting :exec
INSERT INTO system_settings (key, value)
VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type SetSystemSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetSystemSetting(ctx context.Context, arg SetSystemSettingParams) error {
	_, err := q.exec(ctx, q.setSystemSettingStmt, setSystemSetting, arg.Key, arg.Value)
	return err
}
