// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package database

import (
	"context"
)

const addTagToAsset = `-- name: AddTagToAsset :exec
INSERT INTO asset_tags (asset_id, tag_id)
VALUES (?, ?)
ON CONFLICT DO NOTHING
`

type AddTagToAssetParams struct {
	AssetID int64 `json:"assetId"`
	TagID   int64 `json:"tagId"`
}

func (q *Queries) AddTagToAsset(ctx context.Context, arg AddTagToAssetParams) error {
	_, err := q.exec(ctx, q.addTagToAssetStmt, addTagToAsset, arg.AssetID, arg.TagID)
	return err
}

const clearTagsForAsset = `-- name: ClearTagsForAsset :exec
DELETE FROM asset_tags
WHERE asset_id = ?
`

func (q *Queries) ClearTagsForAsset(ctx context.Context, assetID int64) error {
	_, err := q.exec(ctx, q.clearTagsForAssetStmt, clearTagsForAsset, assetID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name) VALUES (?)
ON CONFLICT(name) DO UPDATE SET name=name
RETURNING id, name, date_created
`

func (q *Queries) CreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.queryRow(ctx, q.createTagStmt, createTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.DateCreated)
	return i, err
}

const getAllTags = `-- name: GetAllTags :many
SELECT id, name, date_created FROM tags ORDER BY name ASC
`

func (q *Queries) GetAllTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.query(ctx, q.getAllTagsStmt, getAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.DateCreated); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, date_created FROM tags WHERE name = ? LIMIT 1
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.queryRow(ctx, q.getTagByNameStmt, getTagByName, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.DateCreated)
	return i, err
}

const getTagsByAssetID = `-- name: GetTagsByAssetID :many
SELECT t.id, t.name, t.date_created
FROM tags t
JOIN asset_tags at ON t.id = at.tag_id
WHERE at.asset_id = ?
ORDER BY t.name ASC
`

func (q *Queries) GetTagsByAssetID(ctx context.Context, assetID int64) ([]Tag, error) {
	rows, err := q.query(ctx, q.getTagsByAssetIDStmt, getTagsByAssetID, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.DateCreated); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsNamesByAssetID = `-- name: GetTagsNamesByAssetID :many
SELECT t.name
FROM tags t
JOIN asset_tags at ON t.id = at.tag_id
WHERE at.asset_id = ?
ORDER BY t.name ASC
`

func (q *Queries) GetTagsNamesByAssetID(ctx context.Context, assetID int64) ([]string, error) {
	rows, err := q.query(ctx, q.getTagsNamesByAssetIDStmt, getTagsNamesByAssetID, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT t.id, t.name, COUNT(at.asset_id) as asset_count
FROM tags t
LEFT JOIN asset_tags at ON t.id = at.tag_id
GROUP BY t.id
ORDER BY asset_count DESC
`

type ListTagsRow struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	AssetCount int64  `json:"assetCount"`
}

func (q *Queries) ListTags(ctx context.Context) ([]ListTagsRow, error) {
	rows, err := q.query(ctx, q.listTagsStmt, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsRow
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.AssetCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromAsset = `-- name: RemoveTagFromAsset :exec
DELETE FROM asset_tags
WHERE asset_id = ? AND tag_id = ?
`

type RemoveTagFromAssetParams struct {
	AssetID int64 `json:"assetId"`
	TagID   int64 `json:"tagId"`
}

func (q *Queries) RemoveTagFromAsset(ctx context.Context, arg RemoveTagFromAssetParams) error {
	_, err := q.exec(ctx, q.removeTagFromAssetStmt, removeTagFromAsset, arg.AssetID, arg.TagID)
	return err
}
