// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RestoreWindow() {
  return window["go"]["app"]["App"]["RestoreWindow"]();
}

export function OpenInExplorer(arg1) {
  return window["go"]["app"]["App"]["OpenInExplorer"](arg1);
}

export function OpenInDefaultApp(arg1) {
  return window["go"]["app"]["App"]["OpenInDefaultApp"](arg1);
}
