// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppVersion():Promise<string>;

export function OpenInDefaultApp(arg1:string):Promise<void>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function RestoreWindow():Promise<void>;
