// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAssetToMaterialSet(arg1, arg2) {
  return window['go']['app']['AssetService']['AddAssetToMaterialSet'](arg1, arg2);
}

export function DeleteAssetsPermanently(arg1) {
  return window['go']['app']['AssetService']['DeleteAssetsPermanently'](arg1);
}

export function GetAssetById(arg1) {
  return window['go']['app']['AssetService']['GetAssetById'](arg1);
}

export function GetAssetVersions(arg1) {
  return window['go']['app']['AssetService']['GetAssetVersions'](arg1);
}

export function GetAssets(arg1) {
  return window['go']['app']['AssetService']['GetAssets'](arg1);
}

export function GetLibraryStats() {
  return window['go']['app']['AssetService']['GetLibraryStats']();
}

export function GetSidebarStats() {
  return window['go']['app']['AssetService']['GetSidebarStats']();
}

export function GetThumbnailData(arg1) {
  return window['go']['app']['AssetService']['GetThumbnailData'](arg1);
}

export function MigrateThumbnailPaths() {
  return window['go']['app']['AssetService']['MigrateThumbnailPaths']();
}

export function RemoveAssetFromMaterialSet(arg1, arg2) {
  return window['go']['app']['AssetService']['RemoveAssetFromMaterialSet'](arg1, arg2);
}

export function RenameAsset(arg1, arg2) {
  return window['go']['app']['AssetService']['RenameAsset'](arg1, arg2);
}

export function RestoreAssets(arg1) {
  return window['go']['app']['AssetService']['RestoreAssets'](arg1);
}

export function SetAssetHidden(arg1, arg2) {
  return window['go']['app']['AssetService']['SetAssetHidden'](arg1, arg2);
}

export function SetAssetRating(arg1, arg2) {
  return window['go']['app']['AssetService']['SetAssetRating'](arg1, arg2);
}

export function SoftDeleteAssets(arg1) {
  return window['go']['app']['AssetService']['SoftDeleteAssets'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['AssetService']['Startup'](arg1);
}

export function ToggleAssetFavorite(arg1) {
  return window['go']['app']['AssetService']['ToggleAssetFavorite'](arg1);
}

export function UpdateAssetMetadata(arg1, arg2) {
  return window['go']['app']['AssetService']['UpdateAssetMetadata'](arg1, arg2);
}

export function UpdateAssetType(arg1, arg2) {
  return window['go']['app']['AssetService']['UpdateAssetType'](arg1, arg2);
}

export function UpdateTags(arg1, arg2) {
  return window['go']['app']['AssetService']['UpdateTags'](arg1, arg2);
}
