// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {context} from '../models';

export function AddAssetToMaterialSet(arg1:number,arg2:number):Promise<void>;

export function DeleteAssetsPermanently(arg1:Array<number>):Promise<void>;

export function GetAssetById(arg1:number):Promise<app.AssetDetails>;

export function GetAssetVersions(arg1:number):Promise<Array<app.AssetDetails>>;

export function GetAssets(arg1:app.AssetQueryFilters):Promise<app.PagedAssetResult>;

export function GetLibraryStats():Promise<app.LibraryStats>;

export function GetSidebarStats():Promise<app.SidebarStats>;

export function RemoveAssetFromMaterialSet(arg1:number,arg2:number):Promise<void>;

export function RestoreAssets(arg1:Array<number>):Promise<void>;

export function SetAssetHidden(arg1:number,arg2:boolean):Promise<void>;

export function SetAssetRating(arg1:number,arg2:number):Promise<void>;

export function SoftDeleteAssets(arg1:Array<number>):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function ToggleAssetFavorite(arg1:number):Promise<void>;

export function UpdateAssetMetadata(arg1:number,arg2:app.UpdateAssetRequest):Promise<app.AssetDetails>;

export function UpdateAssetType(arg1:number,arg2:string):Promise<void>;

export function UpdateTags(arg1:number,arg2:Array<string>):Promise<void>;
