// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {context} from '../models';

export function Create(arg1:app.CreateMaterialSetRequest):Promise<app.MaterialSet>;

export function Delete(arg1:number):Promise<void>;

export function GetAll():Promise<Array<app.MaterialSet>>;

export function GetById(arg1:number):Promise<app.MaterialSet>;

export function Startup(arg1:context.Context):Promise<void>;

export function Update(arg1:number,arg2:app.CreateMaterialSetRequest):Promise<app.MaterialSet>;
