// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['app']['MaterialSetService']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['app']['MaterialSetService']['Delete'](arg1);
}

export function GetAll() {
  return window['go']['app']['MaterialSetService']['GetAll']();
}

export function GetById(arg1) {
  return window['go']['app']['MaterialSetService']['GetById'](arg1);
}

export function SetMaterialSetCoverFromFile(arg1, arg2) {
  return window['go']['app']['MaterialSetService']['SetMaterialSetCoverFromFile'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['app']['MaterialSetService']['Startup'](arg1);
}

export function Update(arg1, arg2) {
  return window['go']['app']['MaterialSetService']['Update'](arg1, arg2);
}
