// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAll() {
  return window['go']['app']['TagService']['GetAll']();
}

export function Startup(arg1) {
  return window['go']['app']['TagService']['Startup'](arg1);
}