// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddExtensions(arg1) {
  return window['go']['services']['Scanner']['AddExtensions'](arg1);
}

export function GetConfig() {
  return window['go']['services']['Scanner']['GetConfig']();
}

export function GetPredefinedPalette() {
  return window['go']['services']['Scanner']['GetPredefinedPalette']();
}

export function IsExtensionAllowed(arg1) {
  return window['go']['services']['Scanner']['IsExtensionAllowed'](arg1);
}

export function RemoveExtension(arg1) {
  return window['go']['services']['Scanner']['RemoveExtension'](arg1);
}

export function StartScan() {
  return window['go']['services']['Scanner']['StartScan']();
}

export function Startup(arg1) {
  return window['go']['services']['Scanner']['Startup'](arg1);
}

export function StopScan() {
  return window['go']['services']['Scanner']['StopScan']();
}
