// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function AddExtensions(arg1:Array<string>):Promise<void>;

export function GetConfig():Promise<services.ScannerConfig>;

export function GetPredefinedPalette():Promise<Array<services.PaletteColor>>;

export function IsExtensionAllowed(arg1:string):Promise<boolean>;

export function RemoveExtension(arg1:string):Promise<void>;

export function StartScan():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopScan():Promise<void>;
