// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolder(arg1) {
  return window['go']['services']['SettingsService']['AddFolder'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['services']['SettingsService']['DeleteFolder'](arg1);
}

export function GetFolders() {
  return window['go']['services']['SettingsService']['GetFolders']();
}

export function OpenFile(arg1) {
  return window['go']['services']['SettingsService']['OpenFile'](arg1);
}

export function OpenFolderPicker() {
  return window['go']['services']['SettingsService']['OpenFolderPicker']();
}

export function OpenInExplorer(arg1) {
  return window['go']['services']['SettingsService']['OpenInExplorer'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['SettingsService']['Startup'](arg1);
}

export function UpdateFolderStatus(arg1, arg2) {
  return window['go']['services']['SettingsService']['UpdateFolderStatus'](arg1, arg2);
}

export function ValidatePath(arg1) {
  return window['go']['services']['SettingsService']['ValidatePath'](arg1);
}
