// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {context} from '../models';

export function AddFolder(arg1:string):Promise<database.ScanFolder>;

export function DeleteFolder(arg1:number):Promise<void>;

export function GetFolders():Promise<Array<database.ScanFolder>>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateFolderStatus(arg1:number,arg2:boolean):Promise<database.ScanFolder>;

export function ValidatePath(arg1:string):Promise<boolean>;
