// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Shutdown():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function Unwatch(arg1:string):Promise<void>;

export function Watch(arg1:string):Promise<void>;
