// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';
import {context} from '../models';

export function AddFolder(arg1:string):Promise<settings.ScanFolderDTO>;

export function DeleteFolder(arg1:number):Promise<void>;

export function GetFolders():Promise<Array<settings.ScanFolderDTO>>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolderPicker():Promise<string>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateFolderStatus(arg1:number,arg2:boolean):Promise<settings.ScanFolderDTO>;

export function ValidatePath(arg1:string):Promise<boolean>;
